HeThongThueXe/HeThongThueXe/Controllers/AdminContractsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HeThongThueXe.Models;
using System.Text.RegularExpressions;

namespace HeThongThueXe.Controllers
{
    public class AdminContractsController : Controller
    {
        private QLHeThongThueXeEntities2 db = new QLHeThongThueXeEntities2();

        // GET: AdminContracts
        public async Task<ActionResult> Index()
        {
            var hopDongThueXes = db.HopDongThueXes;
            return View(await hopDongThueXes.ToListAsync());
        }

        // GET: AdminContracts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopDongThueXe hopDongThueXe = await db.HopDongThueXes.FindAsync(id);
            if (hopDongThueXe == null)
            {
                return HttpNotFound();
            }
            return View(hopDongThueXe);
        }

        // GET: AdminContracts/Create
        [HttpGet]
        public ActionResult Create(int idXe)
        {
            Session["IDxe"] = idXe;
            Session["HinhAnh"] = db.Xes.Where(x => x.ID == idXe).FirstOrDefault().HinhAnh;
            Session["BienSo"] = db.Xes.Where(x => x.ID == idXe).FirstOrDefault().BienSo;
            ViewBag.DDGiao = new SelectList(DDGX());
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string CMND, string TGGiao, string TGTra, string DDGiao)
        {

            if (ModelState.IsValid)
            {
                Xe xe = new Xe();
                CarViewModel car = new CarViewModel();
                HopDongThueXe hopDongThueXe = new HopDongThueXe();
                hopDongThueXe.IDKH = int.Parse(Session["IDUser"].ToString());
                hopDongThueXe.IDXe = int.Parse(Session["IDxe"].ToString());
                CMND = CMND.Trim();
                Regex trimmer = new Regex(@"\s\s+");
                CMND = trimmer.Replace(CMND, " ");
                hopDongThueXe.CMND = CMND;
                hopDongThueXe.TGGiaoXe = TGGiao;
                hopDongThueXe.TGTraXe = TGTra;
                hopDongThueXe.DiaDiemGiaoXe = DDGiao.Trim();
                hopDongThueXe.IDTrangThaiHD = 1;
                if (TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe) < 0)
                {
                    string temp = hopDongThueXe.TGGiaoXe;
                    hopDongThueXe.TGGiaoXe = hopDongThueXe.TGTraXe;
                    hopDongThueXe.TGTraXe = temp;
                    hopDongThueXe.SoNgayThue = TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe);
                }
                else if (TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe) == 0)
                {
                    hopDongThueXe.SoNgayThue = 1;
                }
                else
                {
                    hopDongThueXe.SoNgayThue = TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe);
                }

                xe = db.Xes.Where(x => x.ID == hopDongThueXe.IDXe).FirstOrDefault();
                car.GanGT(xe);

                hopDongThueXe.TienDuKien = car.Gia * hopDongThueXe.SoNgayThue;
                hopDongThueXe.ThanhToanTruoc = hopDongThueXe.TienDuKien / 2;
                hopDongThueXe.ConLai = hopDongThueXe.TienDuKien - hopDongThueXe.ThanhToanTruoc;

                db.Configuration.ValidateOnSaveEnabled = false;
                hopDongThueXe.IDKH = int.Parse(Session["IDUser"].ToString());
                hopDongThueXe.IDXe = int.Parse(Session["IDxe"].ToString());
                db.HopDongThueXes.Add(hopDongThueXe);
                xe.TinhTrang = false;
                db.Entry(xe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CheckOut_Success");
            }
            return View();
        }
        public ActionResult CheckOut_Success()
        {
            return View();
        }
        // POST: AdminContracts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.


        // GET: AdminContracts/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    HopDongThueXe hopDongThueXe = await db.HopDongThueXes.FindAsync(id);
        //    if (hopDongThueXe == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.IDKH = new SelectList(db.Users, "IDUser", "HoTen", hopDongThueXe.IDKH);
        //    ViewBag.IDXe = new SelectList(db.Xes, "ID", "HinhAnh", hopDongThueXe.IDXe);
        //    return View(hopDongThueXe);
        //}

        // POST: AdminContracts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeState(HopDongThueXe hopDong)
        {
                HopDongThueXe hopDongThueXe = new HopDongThueXe();
                hopDongThueXe = db.HopDongThueXes.Where(hD => hD.ID == hopDong.ID).FirstOrDefault();
                if(hopDongThueXe.IDTrangThaiHD == 1)
                {
                    hopDongThueXe.IDTrangThaiHD = 2;
                }
                else
                {
                    hopDongThueXe.IDTrangThaiHD = 3;
                    Xe xe = new Xe();
                    xe = db.Xes.Where(x => x.ID == hopDongThueXe.IDXe).FirstOrDefault();
                    xe.TinhTrang = true;
                    CarViewModel car = new CarViewModel();
                    car.GanGT(xe);
                    SoXe soXe = new SoXe();
                    soXe.IDHD = hopDongThueXe.ID;
                    DateTime now = DateTime.Now.Date;
                    soXe.TGTraXeTT = now.ToString("dd/MM/yyyy");
                if(TinhSoNgay(now.ToString(), hopDongThueXe.TGTraXe)>=0)
                {
                    soXe.SoTienTraThem = db.ThamSoes.FirstOrDefault().TyLeTraThemKhiQuaNgay * (decimal)TinhSoNgay(now.ToString(), hopDongThueXe.TGTraXe) * car.Gia + hopDongThueXe.ConLai;
                    soXe.SoTienCanTra = soXe.SoTienTraThem + hopDongThueXe.ThanhToanTruoc;
                }    
                else
                {
                    soXe.SoTienTraThem = 0;
                    soXe.SoTienCanTra = soXe.SoTienTraThem + hopDongThueXe.ThanhToanTruoc;
                }    

                    db.SoXes.Add(soXe);
                    db.Entry(xe).State = EntityState.Modified;

                }
                if (ModelState.IsValid)
                {

                    db.Entry(hopDongThueXe).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            return View("Index");
        }
        // GET: AdminContracts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopDongThueXe hopDongThueXe = await db.HopDongThueXes.FindAsync(id);
            if (hopDongThueXe == null)
            {
                return HttpNotFound();
            }
            return View(hopDongThueXe);
        }

        // POST: AdminContracts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            HopDongThueXe hopDongThueXe = await db.HopDongThueXes.FindAsync(id);
            db.HopDongThueXes.Remove(hopDongThueXe);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult ConfirmContract(string CMND, string TGGiao, string TGTra, string DDGiao)
        {
            Xe xe = new Xe();
            CarViewModel car = new CarViewModel();
            HopDongThueXe hopDongThueXe = new HopDongThueXe();
            hopDongThueXe.IDKH = int.Parse(Session["IDUser"].ToString());
            hopDongThueXe.IDXe = int.Parse(Session["IDxe"].ToString());
            hopDongThueXe.CMND = CMND;
            hopDongThueXe.TGGiaoXe = TGGiao;
            hopDongThueXe.TGTraXe = TGTra;
            hopDongThueXe.DiaDiemGiaoXe = DDGiao;
            if (TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe) < 0)
            {
                string temp = hopDongThueXe.TGGiaoXe;
                hopDongThueXe.TGGiaoXe = hopDongThueXe.TGTraXe;
                hopDongThueXe.TGTraXe = temp;
                hopDongThueXe.SoNgayThue = TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe);
            }
            else if (TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe) == 0)
            {
                hopDongThueXe.SoNgayThue = 1;
            }
            else
            {
                hopDongThueXe.SoNgayThue = TinhSoNgay(hopDongThueXe.TGTraXe, hopDongThueXe.TGGiaoXe);
            }

            xe = db.Xes.Where(x => x.ID == hopDongThueXe.IDXe).FirstOrDefault();
            car.GanGT(xe);

            hopDongThueXe.TienDuKien = car.Gia * hopDongThueXe.SoNgayThue;
            hopDongThueXe.ThanhToanTruoc = hopDongThueXe.TienDuKien / 2;
            hopDongThueXe.ConLai = hopDongThueXe.TienDuKien - hopDongThueXe.ThanhToanTruoc;

            return View(hopDongThueXe);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {

HeThongThueXe/HeThongThueXe/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HeThongThueXe.Models;
using PagedList;
using PagedList.Mvc;
using HeThongThueXe.Pattern;

namespace HeThongThueXe.Controllers
{
    public class CarController : Controller
    {
        QLHeThongThueXeEntities2 db = new QLHeThongThueXeEntities2();
        // GET: Car
        public ActionResult Index(int? page, int? hang,int? cho,string dong)
        {
            int pageNum = (page ?? 1);
            int pageSize = 6;
            //áp dụng singleton
            BrandSingelton.Instance.Init(db);
            List<HangXe> hangXes = BrandSingelton.Instance.listBrand;

            ViewBag.ListBrand = new SelectList(hangXes, "ID", "Ten");
            ViewBag.ListSeat = new SelectList(GetSeats());
            List<CarViewModel> cars = new List<CarViewModel>();
            if(hang==null&&cho==null&&dong==null)
            {
                var lstCar = db.Xes.ToList();
                // áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for(Xe i= xeIterator.First();!xeIterator.IsDone;i=xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }
           else if(hang == null && cho == null)
            {
                var lstCar = db.Xes.Where(x=>x.DongXe.Ten.Contains(dong)).ToList();
                //áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }
            else if (hang == null && dong == null)
            {
                var lstCar = db.Xes.Where(x => x.DongXe.SoCho==cho).ToList();
                //áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }
            else if (dong == null && cho == null)
            {
                var lstCar = db.Xes.Where(x => x.HangXe.ID==hang).ToList();
                //áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }
            else if (hang == null)
            {
                var lstCar = db.Xes.Where(x => x.DongXe.Ten.Contains(dong)&&x.DongXe.SoCho==cho).ToList();
                //áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }
            else if (dong == null)
            {
                var lstCar = db.Xes.Where(x => x.HangXe.ID==hang && x.DongXe.SoCho == cho).ToList();
                //áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }
            else if (cho == null)
            {
                var lstCar = db.Xes.Where(x => x.DongXe.Ten.Contains(dong) && x.HangXe.ID==hang).ToList();
                //áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }
            else
            {
                var lstCar = db.Xes.Where(x => x.DongXe.Ten.Contains(dong) && x.HangXe.ID==hang&&x.DongXe.SoCho==cho).ToList();
                //áp dụng iterator
                IIterator xeIterator = new XeIterator(lstCar);
                for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
                {
                    CarViewModel car = new CarViewModel();
                    car.GanGT(i);
                    cars.Add(car);
                }
                return View(cars.ToPagedList(pageNum, pageSize));
            }    
        }
        public ActionResult CarDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Xe xe = db.Xes.Find(id);
            if (xe == null)
            {
                return HttpNotFound();
            }
            CarViewModel car = new CarViewModel();
            car.GanGT(xe);
            return View(car);
        }
        public List<int>GetSeats()
        {
            List<int> lstCho = new List<int>();
            List<int> lstSeat = new List<int>();
            List<DongXe> xes = db.DongXes.ToList();
            foreach(var xe in xes)
            {
                lstCho.Add(xe.SoCho);
            }
            lstSeat = lstCho.Distinct().ToList();
            return lstSeat;
        }
        public ActionResult BookCar(int IDXe)
        {
            SoDatXe soDatXe = new SoDatXe();
            soDatXe.IDKH = int.Parse(Session["IDUser"].ToString());
            soDatXe.IDXe = IDXe;
            soDatXe.NgayDat = DateTime.Now.Date.ToString("dd/MM/yyyy").Trim();
            if (ModelState.IsValid)
                {
                    db.SoDatXes.Add(soDatXe);
                    db.SaveChanges();
                    return RedirectToAction("CheckOut_Success", "AdminCarBookings");
                }
            return View();
        }
    }
    }

HeThongThueXe/HeThongThueXe/Views/AdminContracts/CheckOut_Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RentSuccessful</title>
</head>
<body >
    <h1 style="text-align:center;vertical-align:middle">Rent Car Successful</h1>
    <h3>
        Contract Terms
    </h3>
    <div>
        <ul>
            <li>
                Your order has been sent to the Shop. You will receive goods at pick-up date
            </li>
            <li>
                The car will be delivered on the date, time and place specified
            </li>
            <li>
                When you pick up the car, please bring your ID card and the deposit
            </li>
            <li>
                The contract will be signed on the day of receipt of the car
            </li>
            <li>
                The car is already filled with gas when it reaches you
            </li>
            <li>
                The car has been thoroughly checked before delivery
            </li>
            <li>
                If you return the car late, you will be fined 150%/day
            </li>
        </ul>
    </div>
    <h3>
        Wish you have a good experience when using our company's services!!
    </h3>
    <a href="@Url.Action("Index","Car")">Continue Rent...</a>
</body>
</html>

HeThongThueXe/HeThongThueXe/Views/AdminContracts/ConfirmContract.cshtml
@model HeThongThueXe.Models.HopDongThueXe

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .trip-form tr.row {
        margin-top: 10px;
        margin-left: 30px;
        margin-right: 30px;
        margin-bottom: 0;
        padding-left: 10px;
        display: table-row;
    }

    .trip-form {
        width: max-content;
        margin-left: auto;
        margin-right: auto;
        margin-top: -500px;
        height: 50%;
        padding-right: 10px;
        padding-bottom: 10px;
        border-radius: 10px;
        display: table;
        font-size: 20px;
    }

    td {
        margin-left: 10px;
        margin-top: 10px;
        display: table-cell;
    }

    .btn {
        color: ghostwhite;
        text-align: center;
        margin-bottom: 10px;
    }

    a.btn {
        color: dodgerblue;
        font-size: small;
    }

    input.btn {
        margin-right: 20px;
        background-color: deepskyblue;
        border-radius: 10px;
        width: max-content;
    }

    .error {
        color: orangered;
    }

    .btn_container {
        margin-top: 10px;
        margin-left: 30%;
        padding-left: 30px;
        padding-right: 30px;
        padding-bottom: 10px;
        display: table-row;
        text-align: center;
    }
</style>

<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay innerpage" style="background-image: url(../Content/images/hero_2.jpg)">
        <div class="container" style="margin-bottom:10px">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">

                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("ContractCreate", "AdminContracts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="trip-form">
        <table>
            <tr class="row">
                <td colspan="3"><h1 style="text-align:center">Contract</h1></td>
            </tr>
            <tr>
                <td class="col">
                    <table>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.User.HoTen):</td>
                            <td class="col_2">@Session["NameUser"]</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.Xe.BienSo):</td>
                            <td class="col_2">@Session["BienSo"]</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.CMND):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.CMND)</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.TGGiaoXe):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.TGGiaoXe)</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.TGTraXe):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.TGTraXe)</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.SoNgayThue):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.SoNgayThue)</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.DiaDiemGiaoXe):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.DiaDiemGiaoXe)</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.TienDuKien):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.TienDuKien)</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.ThanhToanTruoc):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.ThanhToanTruoc)</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.DisplayNameFor(model => model.ConLai):</td>
                            <td class="col_2">@Html.DisplayFor(model => model.ConLai)</td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
        <div class="btn_container">
            <input type="submit" value="Ok" class="btn" style="background-color:deepskyblue" />
            <a href="@Url.Action("Index", "Car")" class="btn btn-default" style="background-color:orangered">Cancel</a>
        </div>
    </div>
}

HeThongThueXe/HeThongThueXe/Views/AdminContracts/Create.cshtml
@model HeThongThueXe.Models.HopDongThueXe

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .trip-form tr.row {
        margin-top: 10px;
        margin-left: 30px;
        margin-right: 30px;
        margin-bottom: 0;
        padding-left: 10px;
        display: table-row;
    }

    .trip-form {
        width: max-content;
        margin-left: auto;
        margin-right: auto;
        margin-top: -570px;
        height: 50%;
        padding-right: 10px;
        padding-bottom: 10px;
        border-radius: 10px;
        display: table;
        font-size: 20px;
    }

    td {
        margin-left: 10px;
        margin-top: 10px;
        display: table-cell;
    }

    .btn {
        color: ghostwhite;
        text-align: center;
        margin-bottom: 10px;
    }

    a.btn {
        color: dodgerblue;
        font-size: small;
    }

    input.btn {
        margin-right: 20px;
        background-color: deepskyblue;
        border-radius: 10px;
        width: max-content;
    }

    .error {
        color: orangered;
    }

    .btn_container {
        margin-top: 10px;
        margin-left: 30%;
        padding-left: 30px;
        padding-right: 30px;
        padding-bottom: 10px;
        display: table-row;
        text-align: center;
    }
</style>
    <div class="ftco-blocks-cover-1">
        <div class="ftco-cover-1 overlay innerpage" style="background-image: url(../Content/images/hero_2.jpg)">
            <div class="container" style="margin-bottom:10px">
                <div class="row align-items-center justify-content-center">
                    <div class="col-lg-6 text-center">

                    </div>
                </div>
            </div>
        </div>
    </div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="trip-form">
        <table>
            <tr class="row">
                <td colspan="3"><h1 style="text-align:center">Infomation For Contract</h1></td>
            </tr>
            <tr>
                <td>
                    <img src="@Session["HinhAnh"].ToString()" style="width:400px;height:400px" />
                </td>
                <td>
                    <table>
                        <tr class="row">
                            <td>@Html.LabelFor(model => model.User.HoTen):</td>
                            <td class="col_2">@Html.Label("idKh", Session["NameUser"].ToString(), new { @class = "form-control" })</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.LabelFor(model => model.CMND):</td>
                            <td class="col_2">@Html.TextBox("CMND", "", new { @class = "form-control" })</td>

                        </tr>
                        <tr>
                            <td></td>
                            <td>@Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.LabelFor(model => model.TGGiaoXe):</td>
                            <td class="col_2">@Html.TextBox("TGGiao", "", new { @type = "date", @class = "form-control" })</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>@Html.ValidationMessageFor(model => model.TGGiaoXe, "", new { @class = "text-danger" })</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.LabelFor(model => model.TGTraXe):</td>
                            <td class="col_2">@Html.TextBox("TGTra", "", new { @type = "date", @class = "form-control" })</td>

                        </tr>
                        <tr>
                            <td></td>
                            <td>@Html.ValidationMessageFor(model => model.TGTraXe, "", new { @class = "text-danger" })</td>
                        </tr>
                        <tr class="row">
                            <td>@Html.LabelFor(model => model.DiaDiemGiaoXe):</td>
                            <td class="col_2">@Html.DropDownList("DDGiao", (IEnumerable<SelectListItem>)ViewBag.DDGiao, "", new { @class = "form-control" })</td>

                        </tr>
                        <tr>
                            <td></td>
                            <td>@Html.ValidationMessageFor(model => model.DiaDiemGiaoXe, "", new { @class = "text-danger" })</td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align:center">
                                    <input type="submit" class="btn btn-default" value="Ok" style="background-color:deepskyblue" />
                                    <a href="@Url.Action("Index", "Car")" class="btn btn-default" style="background-color:orangered">Cancel</a>
                            </td>
                        </tr>
                    </table>
                </td>

            </tr>
        </table>
        
    </div>

}