HeThongThueXe/HeThongThueXe/Controllers/AdminCarViewModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HeThongThueXe.Models;
using HeThongThueXe.Pattern;

namespace HeThongThueXe.Controllers
{
    public class AdminCarViewModelsController : Controller
    {
        private QLHeThongThueXeEntities2 db = new QLHeThongThueXeEntities2();

        // GET: AdminCarViewModels
        public ActionResult Index()
        {
            List<Xe> xes = db.Xes.ToList();
            List<CarViewModel> cars = new List<CarViewModel>();
            //áp dụng iterator
            IIterator xeIterator = new XeIterator(xes);
            for (Xe i = xeIterator.First(); !xeIterator.IsDone; i = xeIterator.Next())
            {
                CarViewModel car = new CarViewModel();
                car.GanGT(i);
                cars.Add(car);
            }
            return View(cars);
        }

        // GET: AdminCarViewModels/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Xe xe = await db.Xes.FindAsync(id);
        //    if (xe == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(xe);
        //}

        // GET: AdminCarViewModels/Create
        public ActionResult Create()
        {
            BrandSingelton.Instance.Init(db);
            ViewBag.IDDongXe = new SelectList(BrandSingelton.Instance.listBrand, "ID", "Ten");
            ViewBag.IDHangXe = new SelectList(BrandSingelton.Instance.listBrand, "ID", "Ten");
            return View();
        }

        // POST: AdminCarViewModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,HinhAnh,TinhTrang,BienSo,IDDongXe,IDHangXe,NamSX,TyLeGia,GhiChu")] Xe xe)
        {
            if (ModelState.IsValid)
            {
                db.Xes.Add(xe);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IDDongXe = new SelectList(db.DongXes, "ID", "Ten", xe.IDDongXe);
            ViewBag.IDHangXe = new SelectList(db.HangXes, "ID", "Ten", xe.IDHangXe);
            return View(xe);
        }
        public async Task<ActionResult> Duplicate(int id)
        {
            ConcreteprototypeXe p1 = new ConcreteprototypeXe(db.Xes.Find(id));
            ConcreteprototypeXe c1 =(ConcreteprototypeXe) p1.Clone();
            Xe xe = c1.Xe;
            if (ModelState.IsValid)
            {
                db.Xes.Add(xe);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IDDongXe = new SelectList(db.DongXes, "ID", "Ten", xe.IDDongXe);
            ViewBag.IDHangXe = new SelectList(db.HangXes, "ID", "Ten", xe.IDHangXe);
            return View(xe);
        }

        // GET: AdminCarViewModels/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Xe xe = await db.Xes.FindAsync(id);
            if (xe == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDDongXe = new SelectList(db.DongXes, "ID", "Ten", xe.IDDongXe);
            BrandSingelton.Instance.Init(db);
            ViewBag.IDHangXe = new SelectList(BrandSingelton.Instance.listBrand, "ID", "Ten", xe.IDHangXe);
            return View(xe);
        }

        // POST: AdminCarViewModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,HinhAnh,TinhTrang,BienSo,IDDongXe,IDHangXe,NamSX,TyLeGia,GhiChu")] Xe xe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(xe).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IDDongXe = new SelectList(db.DongXes, "ID", "Ten", xe.IDDongXe);
            BrandSingelton.Instance.Init(db);
            ViewBag.IDHangXe = new SelectList(BrandSingelton.Instance.listBrand, "ID", "Ten", xe.IDHangXe);
            return View(xe);
        }

        // GET: AdminCarViewModels/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Xe xe = await db.Xes.FindAsync(id);
            if (xe == null)
            {
                return HttpNotFound();
            }
            return View(xe);
        }

        // POST: AdminCarViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Xe xe = await db.Xes.FindAsync(id);
            db.Xes.Remove(xe);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeThongThueXe/HeThongThueXe/Views/AdminCarViewModels/Create.cshtml
@model HeThongThueXe.Models.Xe

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDDongXe, "Car name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IDDongXe", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDDongXe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BienSo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BienSo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BienSo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NamSX, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NamSX, new { htmlAttributes = new { @class = "form-control" ,@type="number",@min=1800,@max=2022,@value=2018} })
            @Html.ValidationMessageFor(model => model.NamSX, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDHangXe, "Brand", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IDHangXe", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDHangXe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TinhTrang, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.TinhTrang)
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TyLeGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TyLeGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TyLeGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" style="background-color:deepskyblue" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HeThongThueXe/HeThongThueXe/Views/AdminCarViewModels/Delete.cshtml
@model HeThongThueXe.Models.Xe

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .table_header {
        text-align: left;
        font-weight: bolder;
        padding-right: 10px;
    }

    table.info {
        margin-left: 10px;
    }

    .delete {
        background-color: orangered
    }

    .donVi {
        font-size: small;
    }
</style>
<h2>Delete</h2>
<hr />
<h3>Are you sure you want to delete this?</h3>
<div class="container">
    <table>
        <tr>
            <td>
                <div class="col">
                    <img src="@Url.Content(Model.HinhAnh)" style="width:500px; height:400px" />
                </div>
            </td>
            <td>
                <table class="info">
                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.DongXe.Ten)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.DongXe.Ten)
                        </td>
                    </tr>
                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.BienSo)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.BienSo)
                        </td>
                    </tr>
                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.HangXe.Ten)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.HangXe.Ten)
                        </td>
                    </tr>

                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.DongXe.SoCho)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.DongXe.SoCho)
                        </td>
                    </tr>
                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.NamSX)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.NamSX)
                        </td>
                    </tr>
                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.GhiChu)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.GhiChu)
                        </td>
                    </tr>
                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.TyLeGia)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.TyLeGia)
                        </td>
                    </tr>
                    <tr>
                        <td class="table_header">
                            @Html.DisplayNameFor(model => model.TinhTrang)
                        </td>

                        <td>
                            @if (Model.TinhTrang == true)
                            {
                                <p>Stock</p>
                            }
                            else
                            {
                                <p>Out of stock</p>
                            }
                        </td>
                    </tr>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.ID)
                        <tr>
                            <td colspan="2" style=" color:aliceblue ;text-align:center">
                                <input type="submit" class="btn btn-default" style="background-color:orangered" value="Delete" />
                                @Html.ActionLink("Back to List", "Index")
                            </td>
                        </tr>
                    }

                </table>
            </td>
        </tr>
    </table>
</div>

HeThongThueXe/HeThongThueXe/Views/AdminCarViewModels/Details.cshtml
@model HeThongThueXe.Models.Xe

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Xe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BienSo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BienSo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NamSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TyLeGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TyLeGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DongXe.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DongXe.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HangXe.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HangXe.Ten)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HeThongThueXe/HeThongThueXe/Views/AdminCarViewModels/Edit.cshtml
@model HeThongThueXe.Models.Xe

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDDongXe, "Car name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IDDongXe", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDDongXe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BienSo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BienSo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BienSo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NamSX, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NamSX, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NamSX, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDHangXe, "Brand", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IDHangXe", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDHangXe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TinhTrang, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.TinhTrang)
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TyLeGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TyLeGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TyLeGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" style="background-color:lightgreen" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HeThongThueXe/HeThongThueXe/Views/AdminCarViewModels/Index.cshtml
@model IEnumerable<HeThongThueXe.Models.CarViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    table.table {
        vertical-align: middle;
        text-align: center
    }
    th {
        vertical-align: middle;
        text-align: center
    }
</style>

<h2>Cars</h2>

<p style="float:right">
    <a href="@Url.Action("Create", "AdminCarViewModels")">Create New</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DongXe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BienSo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NSX)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HangXe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoCho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GhiChu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tinhtrang)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        <img src="@Url.Content(item.Image)" style="width:100px;height:100px" />
    </td>
    <td>
        @Html.DisplayFor(model => item.DongXe)
    </td>
    <td>
        @Html.DisplayFor(model => item.BienSo)
    </td>
    <td>
        @Html.DisplayFor(model => item.NSX)
    </td>
    <td>
        @Html.DisplayFor(model => item.HangXe)
    </td>
    <td>
        @Html.DisplayFor(model => item.SoCho)
    </td>
    <td>
        $@Html.DisplayFor(model => item.Gia)/day
    </td>
    <td>
        @Html.DisplayFor(model => item.GhiChu)
    </td>
    <td>
        @Html.DisplayFor(model => item.Tinhtrang)
    </td>
    <td>
        <a href="@Url.Action("Edit","AdminCarViewModels",new{id=item.ID})" style="color:lightgreen">Edit</a>
        <a href="@Url.Action("Delete","AdminCarViewModels",new{id=item.ID})" style="color: orangered">Delete</a>
        <a href="@Url.Action("Duplicate","AdminCarViewModels",new{id=item.ID})" style="color: yellow">Duplicate</a>
    </td>
</tr>
}

</table>